version: "3"
services:
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        ports:
                - 9090:9090
        volumes:
                - "./prometheus:/etc/prometheus"
                - prometheus-data:/prometheus
        restart: always
        command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

    node_exporter:
        image: prom/node-exporter
        container_name: node-exporter
        ports:
            - 9100:9100
        pid: host
        restart: always

    alertmanager:
        image: prom/alertmanager
        container_name: alertmanager
        ports:
                - 9093:9093
        volumes:
                - "./alertmanager:/config"
                - alertmanager-data:/data
        restart: unless-stopped
        command: --config.file=/config/alertmanager.yml --log.level=debug 

volumes:
  prometheus-data:

  alertmanager-data: