route:
  receiver: 'mail'
  repeat_interval: 4h
  group_by: [ alertname ]

receivers:
  - name: 'mail'
    email_configs:
      - smarthost:'smtp.gmail.com:465'
        auth_username: 'mail@gmail.com'
        auth_password: 'mdp'
        from: 'mail@gmail.com'
        to: 'mail@gmail.com'
